# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_main_compositor.ui'
#
# Created: Mon Aug 25 13:49:11 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageCompositor(object):
    def setupUi(self, ImageCompositor):
        ImageCompositor.setObjectName(_fromUtf8("ImageCompositor"))
        ImageCompositor.resize(720, 480)
        self.gridLayout = QtGui.QGridLayout(ImageCompositor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(ImageCompositor)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget_left = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left.sizePolicy().hasHeightForWidth())
        self.widget_left.setSizePolicy(sizePolicy)
        self.widget_left.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_left.setObjectName(_fromUtf8("widget_left"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_left)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget_io = QtGui.QWidget(self.widget_left)
        self.widget_io.setMinimumSize(QtCore.QSize(0, 125))
        self.widget_io.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_io.setObjectName(_fromUtf8("widget_io"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_io)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.stackwidget_importer = QtGui.QStackedWidget(self.widget_io)
        self.stackwidget_importer.setObjectName(_fromUtf8("stackwidget_importer"))
        self.page_image = QtGui.QWidget()
        self.page_image.setObjectName(_fromUtf8("page_image"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_image)
        self.gridLayout_6.setMargin(3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.edit_imagename = QtGui.QLineEdit(self.page_image)
        self.edit_imagename.setObjectName(_fromUtf8("edit_imagename"))
        self.gridLayout_6.addWidget(self.edit_imagename, 0, 0, 1, 1)
        self.but_imagebrowse = QtGui.QPushButton(self.page_image)
        self.but_imagebrowse.setObjectName(_fromUtf8("but_imagebrowse"))
        self.gridLayout_6.addWidget(self.but_imagebrowse, 0, 1, 1, 1)
        self.but_imageadd = QtGui.QPushButton(self.page_image)
        self.but_imageadd.setObjectName(_fromUtf8("but_imageadd"))
        self.gridLayout_6.addWidget(self.but_imageadd, 1, 0, 1, 2)
        self.stackwidget_importer.addWidget(self.page_image)
        self.page_dir = QtGui.QWidget()
        self.page_dir.setObjectName(_fromUtf8("page_dir"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_dir)
        self.gridLayout_8.setMargin(1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.but_dirbrowse = QtGui.QPushButton(self.page_dir)
        self.but_dirbrowse.setObjectName(_fromUtf8("but_dirbrowse"))
        self.gridLayout_8.addWidget(self.but_dirbrowse, 0, 1, 1, 1)
        self.edit_dirname = QtGui.QLineEdit(self.page_dir)
        self.edit_dirname.setObjectName(_fromUtf8("edit_dirname"))
        self.gridLayout_8.addWidget(self.edit_dirname, 0, 0, 1, 1)
        self.edit_imagepattern = QtGui.QLineEdit(self.page_dir)
        self.edit_imagepattern.setObjectName(_fromUtf8("edit_imagepattern"))
        self.gridLayout_8.addWidget(self.edit_imagepattern, 1, 0, 1, 1)
        self.but_diradd = QtGui.QPushButton(self.page_dir)
        self.but_diradd.setObjectName(_fromUtf8("but_diradd"))
        self.gridLayout_8.addWidget(self.but_diradd, 1, 1, 1, 1)
        self.stackwidget_importer.addWidget(self.page_dir)
        self.gridLayout_3.addWidget(self.stackwidget_importer, 1, 0, 1, 2)
        self.groupbox_importer = QtGui.QGroupBox(self.widget_io)
        self.groupbox_importer.setAlignment(QtCore.Qt.AlignCenter)
        self.groupbox_importer.setCheckable(False)
        self.groupbox_importer.setObjectName(_fromUtf8("groupbox_importer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupbox_importer)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbut_image = QtGui.QRadioButton(self.groupbox_importer)
        self.rbut_image.setObjectName(_fromUtf8("rbut_image"))
        self.horizontalLayout.addWidget(self.rbut_image)
        self.rbut_dir = QtGui.QRadioButton(self.groupbox_importer)
        self.rbut_dir.setObjectName(_fromUtf8("rbut_dir"))
        self.horizontalLayout.addWidget(self.rbut_dir)
        self.gridLayout_3.addWidget(self.groupbox_importer, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget_io, 0, 0, 1, 2)
        self.table_images = QtGui.QTableWidget(self.widget_left)
        self.table_images.setMinimumSize(QtCore.QSize(0, 250))
        self.table_images.setObjectName(_fromUtf8("table_images"))
        self.table_images.setColumnCount(0)
        self.table_images.setRowCount(0)
        self.gridLayout_2.addWidget(self.table_images, 1, 0, 1, 1)
        self.widget_right = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right.sizePolicy().hasHeightForWidth())
        self.widget_right.setSizePolicy(sizePolicy)
        self.widget_right.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_right.setObjectName(_fromUtf8("widget_right"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_right)
        self.gridLayout_4.setMargin(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_algo = QtGui.QWidget(self.widget_right)
        self.widget_algo.setObjectName(_fromUtf8("widget_algo"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_algo)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget_algo)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackwidget_algo_details = QtGui.QStackedWidget(self.widget_algo)
        self.stackwidget_algo_details.setObjectName(_fromUtf8("stackwidget_algo_details"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackwidget_algo_details.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackwidget_algo_details.addWidget(self.page_2)
        self.gridLayout_5.addWidget(self.stackwidget_algo_details, 3, 0, 1, 1)
        self.cbox_algo = QtGui.QComboBox(self.widget_algo)
        self.cbox_algo.setObjectName(_fromUtf8("cbox_algo"))
        self.gridLayout_5.addWidget(self.cbox_algo, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_algo)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_algo, 0, 0, 1, 1)
        self.widget_output = QtGui.QWidget(self.widget_right)
        self.widget_output.setMinimumSize(QtCore.QSize(0, 125))
        self.widget_output.setObjectName(_fromUtf8("widget_output"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget_output)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label = QtGui.QLabel(self.widget_output)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.edit_outfilename = QtGui.QLineEdit(self.widget_output)
        self.edit_outfilename.setObjectName(_fromUtf8("edit_outfilename"))
        self.gridLayout_9.addWidget(self.edit_outfilename, 1, 0, 1, 1)
        self.but_outbrowse = QtGui.QPushButton(self.widget_output)
        self.but_outbrowse.setObjectName(_fromUtf8("but_outbrowse"))
        self.gridLayout_9.addWidget(self.but_outbrowse, 1, 1, 1, 1)
        self.combox_outformat = QtGui.QComboBox(self.widget_output)
        self.combox_outformat.setObjectName(_fromUtf8("combox_outformat"))
        self.gridLayout_9.addWidget(self.combox_outformat, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.widget_output, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ImageCompositor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(ImageCompositor)
        self.stackwidget_importer.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ImageCompositor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ImageCompositor.reject)
        QtCore.QMetaObject.connectSlotsByName(ImageCompositor)

    def retranslateUi(self, ImageCompositor):
        ImageCompositor.setWindowTitle(_translate("ImageCompositor", "Dialog", None))
        self.edit_imagename.setPlaceholderText(_translate("ImageCompositor", "Select file", None))
        self.but_imagebrowse.setText(_translate("ImageCompositor", "Browse", None))
        self.but_imageadd.setText(_translate("ImageCompositor", "Add", None))
        self.but_dirbrowse.setText(_translate("ImageCompositor", "Browse", None))
        self.edit_dirname.setPlaceholderText(_translate("ImageCompositor", "Select directory", None))
        self.edit_imagepattern.setPlaceholderText(_translate("ImageCompositor", "Image filename pattern", None))
        self.but_diradd.setText(_translate("ImageCompositor", "Import", None))
        self.groupbox_importer.setTitle(_translate("ImageCompositor", "Import Image", None))
        self.rbut_image.setText(_translate("ImageCompositor", "Add images", None))
        self.rbut_dir.setText(_translate("ImageCompositor", "Import directory", None))
        self.label_2.setText(_translate("ImageCompositor", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Composite Algorithm</span></p></body></html>", None))
        self.label_3.setText(_translate("ImageCompositor", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Details</span></p></body></html>", None))
        self.label.setText(_translate("ImageCompositor", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Output</span></p></body></html>", None))
        self.edit_outfilename.setPlaceholderText(_translate("ImageCompositor", "Output filename", None))
        self.but_outbrowse.setText(_translate("ImageCompositor", "Browse", None))

